name: Build and upload

on:
  workflow_dispatch:
    inputs:
      tag-override:
        description: "Tag"
        type: string
        required: false

env:
  java-version: "17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Apply tag override and parse ref"
        uses: bisgardo/github-action-parse-ref@v1
        id: ref
        with:
          ref: "${{github.event.inputs.tag-override || github.ref}}"
          default-ref-type: tags
      - name: Fail if ref is not a tag
        if: "steps.ref.outputs.ref-type != 'tags'"
        run: exit 1
      - uses: actions/checkout@v3
        with:
          ref: "${{steps.ref.outputs.ref-name}}"
      - name: "Set up JDK"
        uses: actions/setup-java@v3
        with:
          java-version: "${{env.java-version}}"
          distribution: temurin
          cache: gradle # caches dependencies (https://github.com/actions/setup-java#caching-packages-dependencies)
      - name: "Check that tag matches the version name declared in 'build.gradle'"
        run: |
          v="$(./gradlew -q printVersionName)"
          [[ "${{steps.ref.outputs.ref-name}}" = ${v}-* ]]
      - name: "Build project and run unit tests"
        run: ./gradlew build
      - name: Store generated release build APK for stagenet
        uses: actions/upload-artifact@v3
        with:
          name: apk-stagenet-release
          path: "${{github.workspace}}/app/build/outputs/apk/staging/release/"
      - name: "Store generated release build APK for testnet"
        uses: actions/upload-artifact@v3
        with:
          name: apk-testnet-release
          path: "${{github.workspace}}/app/build/outputs/apk/prodTestNet/release/"
      - name: "Store generated release build APK for mainnet"
        uses: actions/upload-artifact@v3
        with:
          name: apk-mainnet-release
          path: "${{github.workspace}}/app/build/outputs/apk/prodMainNet/release/"
